### ISSUE TITLE
Add explanation of how to pass options

### ISSUE THREAD

**Issue by GeoffreyBooth** [nolemmings/browserify-coffeelint#1]
I’m using Browserify via Gulp, so for me I pass options to my transforms via `package.json`:

```
  "browserify": {
    "transform": [
      [
        "browserify-coffeelint",
        {
          "arrow_spacing": {
            "name": "arrow_spacing",
            "level": "error"
          }
        }
      ]
    }
```

This would be something useful to add to the docs. I wish there was a way to load options from a `coffeelint.json` file, rather than cluttering up my `package.json`.

**Comment by JorritPosthuma** [comment]
It now detects the `coffeelint.json` file 😄. Thnx to @rsboarder!
