### ISSUE TITLE
Use the ConfigFinder provided by coffeelint

### ISSUE THREAD

**Issue by AsaAyers** [nolemmings/browserify-coffeelint#2]
The CoffeeLint package exposes a `ConfigFinder` so that users can simply configure the _project_. This is ideal when you have multiple developers so you don't end up trying to configure `browserify-coffeelint` and `coffeelint` (commandline), and your editor plugin, and the other developers' editor plugin(s).

See [linter-coffeelint](https://github.com/AtomLinter/linter-coffeelint/blob/master/lib/linter-coffeelint.coffee#L49-L50) for an example. I'm the current maintainer of CoffeeLint, and linter-coffeelint, so just let me know if you run into any trouble with this.

I recommend closing #1 in favor of project level configuration.

**Comment by JorritPosthuma** [comment]
It now detects the `coffeelint.json` file 😄. Thnx to @rsboarder!

**Comment by GeoffreyBooth** [comment]
Thanks so much! You might want to add a note about this to the README.

**Comment by JorritPosthuma** [comment]
Good idea 😊

**Comment by GeoffreyBooth** [comment]
Thanks. I think you meant to write `coffeelint.json`, not `coffeelint.coffee`? Though if it _did_ support reading its options from a CoffeeScript file, that would be awesome.

**Comment by JorritPosthuma** [comment]
Oops, thanks 😊. Using options from a CoffeeScript file is possible using the programmatic API!
