### ISSUE TITLE
How to make browserify fail/error coffeelint errors

### ISSUE THREAD

**Issue by nmccready** [nolemmings/browserify-coffeelint#5]
I need the browserify stream to emit errors; currently I do not see any errors reported back to browserify and it is only pumped out to reporter.

https://github.com/nolemmings/browserify-coffeelint/blob/master/index.coffee#L18

This is useful for making pipelines fail like gulp and browserify.

**Comment by nmccready** [comment]
Working on a PR

**Comment by nmccready** [comment]
#6

**Comment by JorritPosthuma** [comment]
Thanks!! Added your name to the docs too ;)

**Comment by nmccready** [comment]
Thanks @JorritPosthuma no need to do that as it is in the history. But thanks anyways.
